cpu: 
  id : cpu
  title: cpu
  codec: PNG
  graph: LINE
  alpha: 0.6
  legend-color: [232, 218, 239]
  bg-color: [214, 234, 248]
  graph-bg-color: [235, 237, 239]
  interpolate: LINEAR
  width: 800
  height: 500
  x-index: 100
  y-index: [0, 0]
  limit: 100
  unit: '%'
  elements: 
    - element: leap
      color: [180,130,130]
      values: [0, 0, 0]
    - element: system
      color: [180,180,140]
      values: [0, 0, 0]
  in-memory: true
  save-path: monitor/cpu.png
memory: 
  id : memory
  title: memory
  codec: PNG
  graph: AREA
  alpha: 0.6
  legend-color: [232, 218, 239]
  bg-color: [214, 234, 248]
  graph-bg-color: [235, 237, 239]
  interpolate: SPLINE
  width: 800
  height: 500
  x-index: 100
  y-index: [0, 0, 0]
  limit: 34000
  unit: mb
  elements: 
    - element: Physical Used
      color: [133,193,233]
      values: [0, 0, 0]
    - element: Physical Free
      color: [178,186,187]
      values: [0, 0, 0]
    - element: Leap Used
      color: [127,0,244]
      values: [0, 0, 0]
  in-memory: true
  save-path: monitor/memory.png
heap: 
  id : heap
  title: heap
  codec: PNG
  graph: AREA
  alpha: 0.6
  legend-color: [232, 218, 239]
  bg-color: [214, 234, 248]
  graph-bg-color: [235, 237, 239]
  interpolate: SPLINE
  width: 800
  height: 500
  x-index: 100
  y-index: [0, 0, 0, 0]
  limit: 3500
  unit: mb
  elements: 
    - element: Max
      color: [133,157,233]
      values: [0, 0, 0]
    - element: Committed
      color: [233,138,133]
      values: [0, 0, 0]
    - element: Init
      color: [200,133,233]
      values: [0, 0, 0]
    - element: Used
      color: [127,0,244]
      values: [0, 0, 0]
  in-memory: true
  save-path: monitor/heap.png
thread: 
  id : thread
  title: thread
  codec: PNG
  graph: LINE
  alpha: 0.6
  legend-color: [232, 218, 239]
  bg-color: [214, 234, 248]
  graph-bg-color: [235, 237, 239]
  interpolate: SPLINE
  width: 800
  height: 500
  x-index: 100
  y-index: [0, 0, 0, 0]
  limit: 150
  unit: cnt
  elements: 
    - element: Max
      color: [180,130,130]
      values: [0, 0, 0]
    - element: Core
      color: [88,121,203]
      values: [0, 0, 0]
    - element: Active Task
      color: [73, 182, 69]
      values: [0, 0, 0]
    - element: Queued
      color: [239, 44, 21]
      values: [0, 0, 0]
  in-memory: true
  save-path: monitor/thread.png

